FROM ubuntu:22.04

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8

# Bug 6修正: qtbase5-dev を明示 (qmake が Qt ヘッダを見つけるのに必要)
RUN apt-get update && \
    apt-get install -y \
        libqt5serialport5 \
        libqt5serialport5-dev \
        qtbase5-dev \
        qt5-qmake \
        g++ \
        make \
        cmake \
        git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build
